config/routes.rb
Rails.application.routes.draw do
  
  resources :kobolds
  
  resources :thorns
  # For details on he DSL available within this file, see http://guides.rubyonrails.org/routing.html

   get '/farp', to: 'farp#index'
   get '/gobz', to: 'farp#goblin'
   
  root 'static_pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foop.rb
class Foop < ApplicationRecord
end

app/models/kobold.rb
class Kobold < ApplicationRecord
end

app/models/thorn.rb
class Thorn < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/farp_controller.rb
class FarpController < ApplicationController

  def index
    @globber = "hello"
    @fobber = 500

    @boop = [1,2,3,4,5,6, "Jerry"]

    @hoop = []

    # THIS IS A COMMENT code wont be run
    23.times do |zubar|
        @hoop = @hoop + [zubar ]  #is a list
    end
  end

def goblin
  @items = ["staff"]



end







end

app/controllers/kobolds_controller.rb
class KoboldsController < ApplicationController
  before_action :set_kobold, only: [:show, :edit, :update, :destroy]

  # GET /kobolds
  # GET /kobolds.json
  def index
    @kobolds = Kobold.all
  end

  # GET /kobolds/1
  # GET /kobolds/1.json
  def show
  end

  # GET /kobolds/new
  def new
    @kobold = Kobold.new
  end

  # GET /kobolds/1/edit
  def edit
  end

  # POST /kobolds
  # POST /kobolds.json
  def create
    @kobold = Kobold.new(kobold_params)

    respond_to do |format|
      if @kobold.save
        format.html { redirect_to @kobold, notice: 'Kobold was successfully created.' }
        format.json { render :show, status: :created, location: @kobold }
      else
        format.html { render :new }
        format.json { render json: @kobold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kobolds/1
  # PATCH/PUT /kobolds/1.json
  def update
    respond_to do |format|
      if @kobold.update(kobold_params)
        format.html { redirect_to @kobold, notice: 'Kobold was successfully updated.' }
        format.json { render :show, status: :ok, location: @kobold }
      else
        format.html { render :edit }
        format.json { render json: @kobold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kobolds/1
  # DELETE /kobolds/1.json
  def destroy
    @kobold.destroy
    respond_to do |format|
      format.html { redirect_to kobolds_url, notice: 'Kobold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kobold
      @kobold = Kobold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kobold_params
      params.require(:kobold).permit(:name, :level, :hp)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @globber = "hello"
    @fobber = 500

    @boop = [1,2,3,4,5,6, "Jerry"]

    @hoop = []

    # THIS IS A COMMENT code wont be run
    23.times do |zubar|
        @hoop = @hoop + [zubar ]  #is a list
    end

  end

end

app/controllers/thorns_controller.rb
class ThornsController < ApplicationController
  before_action :set_thorn, only: [:show, :edit, :update, :destroy]

  # GET /thorns
  # GET /thorns.json
  def index
    @thorns = Thorn.all
  end

  # GET /thorns/1
  # GET /thorns/1.json
  def show
  end

  # GET /thorns/new
  def new
    @thorn = Thorn.new
  end

  # GET /thorns/1/edit
  def edit
  end

  # POST /thorns
  # POST /thorns.json
  def create
    @thorn = Thorn.new(thorn_params)

    respond_to do |format|
      if @thorn.save
        format.html { redirect_to @thorn, notice: 'Thorn was successfully created.' }
        format.json { render :show, status: :created, location: @thorn }
      else
        format.html { render :new }
        format.json { render json: @thorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thorns/1
  # PATCH/PUT /thorns/1.json
  def update
    respond_to do |format|
      if @thorn.update(thorn_params)
        format.html { redirect_to @thorn, notice: 'Thorn was successfully updated.' }
        format.json { render :show, status: :ok, location: @thorn }
      else
        format.html { render :edit }
        format.json { render json: @thorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thorns/1
  # DELETE /thorns/1.json
  def destroy
    @thorn.destroy
    respond_to do |format|
      format.html { redirect_to thorns_url, notice: 'Thorn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thorn
      @thorn = Thorn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thorn_params
      params.require(:thorn).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kobolds_helper.rb
module KoboldsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/thorns_helper.rb
module ThornsHelper
end

app/views/farp/goblin.html.erb
<h1>
Items are <%= @items %>

</h1>

app/views/farp/index.html.erb
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1>Navbar example</h1>
  <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
  <p>
    <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
  </p>

<div style="background-color:#ada">

<%= @globber %> is a <%= @fobber %>


<ul>
<% @boop.each do |q| %>
  <li> <%= q %> </li>
<% end %>
</ul>

<ul>
<% @hoop.each do |q| %>
  <li> <%= q %> </li>
<% end %>
</ul>


</div>


<%= link_to "AucIt", root_path %>

</div>

app/views/kobolds/_form.html.erb
<%= form_with(model: kobold, local: true) do |form| %>
  <% if kobold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kobold.errors.count, "error") %> prohibited this kobold from being saved:</h2>

      <ul>
      <% kobold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :kobold_name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level, id: :kobold_level %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp, id: :kobold_hp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kobolds/edit.html.erb
<h1>Editing Kobold</h1>

<%= render 'form', kobold: @kobold %>

<%= link_to 'Show', @kobold %> |
<%= link_to 'Back', kobolds_path %>

app/views/kobolds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kobolds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Hp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kobolds.each do |kobold| %>
      <tr>
        <td><%= kobold.name %></td>
        <td><%= kobold.level %></td>
        <td><%= kobold.hp %></td>
        <td><%= link_to 'Show', kobold %></td>
        <td><%= link_to 'Edit', edit_kobold_path(kobold) %></td>
        <td><%= link_to 'Destroy', kobold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kobold', new_kobold_path %>

app/views/kobolds/new.html.erb
<h1>New Kobold</h1>

<%= render 'form', kobold: @kobold %>

<%= link_to 'Back', kobolds_path %>

app/views/kobolds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kobold.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @kobold.level %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @kobold.hp %>
</p>

<%= link_to 'Edit', edit_kobold_path(@kobold) %> |
<%= link_to 'Back', kobolds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">


      <nav class="navbar navbar-light bg-faded">
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
     <%= link_to 'GOBBBO LINK', gobz_path %>
      </li>
      <li class="nav-item">
      <%= link_to 'roooot link', root_path %>
      </li>
      <%= link_to 'farp link', farp_path %>
      <li class="nav-item">
      <%= link_to 'kobolssss', kobolds_path %>
      </li>
      <li class="nav-item">
      <%= link_to 'create new ko', new_kobold_path %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</nav>
      <%= yield %>



    </div> <!-- /container -->


  

   
  </body>
</html>

app/views/static_pages/index.html.erb
<div style="background-color:#ada">

<%= @globber %> is a <%= @fobber %>


<ul>
<% @boop.each do |q| %>
  <li> <%= q %> </li>
<% end %>
</ul>

<ul>
<% @hoop.each do |q| %>
  <li> <%= q %> </li>
<% end %>
</ul>


</div>


<%= link_to "AucIt", root_path %> 

app/views/thorns/_form.html.erb
<%= form_with(model: thorn, local: true) do |form| %>
  <% if thorn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thorn.errors.count, "error") %> prohibited this thorn from being saved:</h2>

      <ul>
      <% thorn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :thorn_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thorns/edit.html.erb
<h1>Editing Thorn</h1>

<%= render 'form', thorn: @thorn %>

<%= link_to 'Show', @thorn %> |
<%= link_to 'Back', thorns_path %>

app/views/thorns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thorns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thorns.each do |thorn| %>
      <tr>
        <td><%= thorn.name %></td>
        <td><%= link_to 'Show', thorn %></td>
        <td><%= link_to 'Edit', edit_thorn_path(thorn) %></td>
        <td><%= link_to 'Destroy', thorn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thorn', new_thorn_path %>

app/views/thorns/new.html.erb
<h1>New Thorn</h1>

<%= render 'form', thorn: @thorn %>

<%= link_to 'Back', thorns_path %>

app/views/thorns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thorn.name %>
</p>

<%= link_to 'Edit', edit_thorn_path(@thorn) %> |
<%= link_to 'Back', thorns_path %>